name: GitHub Contribution 3D Stats

on:
  schedule:
    - cron: '0 6,18 * * 1-5' # Run at 6:00 AM and 6:00 PM on weekdays (Monday to Friday)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: khasmir04
      - name: Commit & Push
        run: |
          git config user.name khasmir04
          git config user.email kcaluscusao@gmail.com
          git add -A .
          git commit -m "docs: update github-profile-3d-contrib"
          git push
