name: GitHub Contribution 3D Stats

on:
  schedule:
    #- cron: '0 */5 * * 1-5' # Run every 5 hours on weekdays (Monday to Friday)
    # - cron: '0 */5 * * 1,4,6' # MTHS
    # - cron: '0 */5 * * 2,4,5' # TTHF
    # - cron: '0 */5 * * 1,2,5' # MTF
    # - cron: '0 */5 * * 0,2,3,6' #TWSS
    - cron: '0 */5 * * 1,3,4,5' # MWTHF
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: khasmir04
      - name: Commit & Push
        run: |
          git config user.name khasmir04
          git config user.email kcaluscusao@gmail.com
          git add -A .
          git commit -m "docs: update github-profile-3d-contrib"
          git push
